export const columns = [
  { name: "No", uid: "no" },
  { name: "Nama Usaha", uid: "nama_usaha" },
  { name: "Identitas SLS", uid: "rt_rw_dusun" },
  { name: "No Urut Bangunan", uid: "no_urut_bangunan" },
  { name: "Aksi", uid: "aksi" },
];

export const dummy = [
  {
    no: 1,
    nama_usaha: "Toko Sembako Makmur",
    wilayah: "RT 001 RW 001 DUSUN SIMO",
    no_urut_bangunan: "B001",
    nama_pemilik_penanggungjawab: "Andi Pratama",
  },
  {
    no: 2,
    nama_usaha: "Restoran Sederhana",
    wilayah: "RT 002 RW 001 DUSUN SIMO",
    no_urut_bangunan: "B002",
    nama_pemilik_penanggungjawab: "Budi Santoso",
  },
  {
    no: 3,
    nama_usaha: "Kafe Kopi Kita",
    wilayah: "RT 003 RW 001 DUSUN SIMO",
    no_urut_bangunan: "B003",
    nama_pemilik_penanggungjawab: "Cici Wulandari",
  },
  {
    no: 4,
    nama_usaha: "Toko Elektronik Jaya",
    wilayah: "RT 004 RW 002 DUSUN NGANGIN",
    no_urut_bangunan: "B004",
    nama_pemilik_penanggungjawab: "Dedi Kurniawan",
  },
  {
    no: 5,
    nama_usaha: "Bengkel Mobil Sejahtera",
    wilayah: "RT 005 RW 002 DUSUN NGANGIN",
    no_urut_bangunan: "B005",
    nama_pemilik_penanggungjawab: "Eka Pratiwi",
  },
  {
    no: 6,
    nama_usaha: "Toko Pakaian Elegan",
    wilayah: "RT 006 RW 002 DUSUN NGANGIN",
    no_urut_bangunan: "B006",
    nama_pemilik_penanggungjawab: "Fajar Setiawan",
  },
  {
    no: 7,
    nama_usaha: "Restoran Seafood Bahari",
    wilayah: "RT 007 RW 003 DUSUN BENDO MALANG",
    no_urut_bangunan: "B007",
    nama_pemilik_penanggungjawab: "Gina Hapsari",
  },
  {
    no: 8,
    nama_usaha: "Kafe Santai",
    wilayah: "RT 008 RW 003 DUSUN BENDO MALANG",
    no_urut_bangunan: "B008",
    nama_pemilik_penanggungjawab: "Hadi Wijaya",
  },
  {
    no: 9,
    nama_usaha: "Toko Alat Tulis Cemerlang",
    wilayah: "RT 009 RW 003 DUSUN BENDO MALANG",
    no_urut_bangunan: "B009",
    nama_pemilik_penanggungjawab: "Intan Melati",
  },
  {
    no: 10,
    nama_usaha: "Bengkel Motor Berkah",
    wilayah: "RT 010 RW 004 DUSUN PEJAGALAN",
    no_urut_bangunan: "B010",
    nama_pemilik_penanggungjawab: "Joko Santosa",
  },
  {
    no: 11,
    nama_usaha: "Toko Buku Cerdas",
    wilayah: "RT 011 RW 004 DUSUN PEJAGALAN",
    no_urut_bangunan: "B011",
    nama_pemilik_penanggungjawab: "Kiki Rahayu",
  },
  {
    no: 12,
    nama_usaha: "Restoran Ayam Penyet Ria",
    wilayah: "RT 012 RW 004 DUSUN PEJAGALAN",
    no_urut_bangunan: "B012",
    nama_pemilik_penanggungjawab: "Lina Oktaviani",
  },
  {
    no: 13,
    nama_usaha: "Kafe Kopi Pagi",
    wilayah: "RT 013 RW 004 DUSUN PEJAGALAN",
    no_urut_bangunan: "B013",
    nama_pemilik_penanggungjawab: "Martha Sari",
  },
  {
    no: 14,
    nama_usaha: "Toko Sembako Sejahtera",
    wilayah: "RT 001 RW 001 DUSUN SIMO",
    no_urut_bangunan: "B014",
    nama_pemilik_penanggungjawab: "Nina Puspitasari",
  },
  {
    no: 15,
    nama_usaha: "Bengkel Sepeda Maju",
    wilayah: "RT 002 RW 001 DUSUN SIMO",
    no_urut_bangunan: "B015",
    nama_pemilik_penanggungjawab: "Oki Setiawan",
  },
  {
    no: 16,
    nama_usaha: "Toko Peralatan Rumah Tangga",
    wilayah: "RT 003 RW 001 DUSUN SIMO",
    no_urut_bangunan: "B016",
    nama_pemilik_penanggungjawab: "Petrus Yulianto",
  },
  {
    no: 17,
    nama_usaha: "Restoran Sederhana Rasa",
    wilayah: "RT 004 RW 002 DUSUN NGANGIN",
    no_urut_bangunan: "B017",
    nama_pemilik_penanggungjawab: "Qori Mutiara",
  },
  {
    no: 18,
    nama_usaha: "Kafe Roti Bakar",
    wilayah: "RT 005 RW 002 DUSUN NGANGIN",
    no_urut_bangunan: "B018",
    nama_pemilik_penanggungjawab: "Rina Cahyani",
  },
  {
    no: 19,
    nama_usaha: "Toko Kebutuhan Sehari-hari",
    wilayah: "RT 006 RW 002 DUSUN NGANGIN",
    no_urut_bangunan: "B019",
    nama_pemilik_penanggungjawab: "Sigit Rahman",
  },
  {
    no: 20,
    nama_usaha: "Bengkel Teknik Terampil",
    wilayah: "RT 007 RW 003 DUSUN BENDO MALANG",
    no_urut_bangunan: "B020",
    nama_pemilik_penanggungjawab: "Tari Lestari",
  },
  {
    no: 21,
    nama_usaha: "Toko Baju Modern",
    wilayah: "RT 008 RW 003 DUSUN BENDO MALANG",
    no_urut_bangunan: "B021",
    nama_pemilik_penanggungjawab: "Ujang Prabowo",
  },
  {
    no: 22,
    nama_usaha: "Restoran Sari Laut",
    wilayah: "RT 009 RW 003 DUSUN BENDO MALANG",
    no_urut_bangunan: "B022",
    nama_pemilik_penanggungjawab: "Vina Maulana",
  },
  {
    no: 23,
    nama_usaha: "Kafe Makan Santai",
    wilayah: "RT 010 RW 004 DUSUN PEJAGALAN",
    no_urut_bangunan: "B023",
    nama_pemilik_penanggungjawab: "Wahyu Prabowo",
  },
  {
    no: 24,
    nama_usaha: "Toko Perlengkapan Olahraga",
    wilayah: "RT 011 RW 004 DUSUN PEJAGALAN",
    no_urut_bangunan: "B024",
    nama_pemilik_penanggungjawab: "Xena Sari",
  },
  {
    no: 25,
    nama_usaha: "Bengkel Mobil Terpercaya",
    wilayah: "RT 012 RW 004 DUSUN PEJAGALAN",
    no_urut_bangunan: "B025",
    nama_pemilik_penanggungjawab: "Yanto Hidayat",
  },
];
